services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: retro-collection-api
    restart: unless-stopped

    # DNS stable pour éviter les erreurs Supabase
    dns:
      - 8.8.8.8
      - 1.1.1.1

    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_OPTIONS: --dns-result-order=ipv4first
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      VERSION: ${VERSION}
      NAME: ${NAME}
      PRODUCT: ${PRODUCT}
      SIDE: ${SIDE}
      VERSION_SHORT: ${VERSION_SHORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

    ports:
      - "${PORT}:${PORT}"

    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nodemon.json:/app/nodemon.json
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules

    command: npm start
